# These are supported funding model platforms

github: felipeanexo
# ko_fi: felipeanexo
# liberapay: felipeanexo
# open_collective: felipeanexo
# otechie: felipeanexo
# patreon: felipeanexo
# tidelift: felipeanexo
# community_bridge: felipeanexo
# issuehunt: felipeanexo
# otechie: felipeanexo
# custom: https://www.paypal.me/felipeanexo 