name: Enable GitHub Pages

on:
  workflow_dispatch:

jobs:
  enable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Enable GitHub Pages
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.repos.createPagesSite({
                owner: context.repo.owner,
                repo: context.repo.repo,
                source: {
                  branch: 'main',
                  path: '/'
                }
              });
              console.log('GitHub Pages enabled successfully!');
            } catch (error) {
              console.log('GitHub Pages might already be enabled or there was an error:', error.message);
            }
